development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: church_app_development
  pool: 5
  username: church_app
  password: churchapp
  template: template0

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: church_app_test
  pool: 5
  username: church_app
  password: churchapp
  template: template0


production:
  adapter: postgresql
  database: app_production
  pool: 5
  timeout: 5000
  template: template0
